urban_project/board/urls.py
from django.urls import path
from . import views


app_name = 'board'

urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),

    path('add/', views.add_advertisement, name='add_advertisement'),
    path('edit/<int:pk>/', views.edit_advertisement, name='edit_advertisement'),
    path('delete/<int:pk>/', views.delete_advertisement, name='delete_advertisement'),
    path('advertisement/<int:pk>/like/', views.like_advertisement, name='like_advertisement'),
    path('advertisement/<int:pk>/dislike/', views.dislike_advertisement, name='dislike_advertisement'),

]

urban_project/urban_project/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views as board_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urban_project/board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver

class Advertisement(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='ad_images/', null=True, blank=True,  storage=FileSystemStorage())
    likes = models.ManyToManyField(User, related_name='liked_advertisements', blank=True)
    dislikes = models.ManyToManyField(User, related_name='disliked_advertisements', blank=True)



    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

    def get_stats(self):
        return {
            'created_advertisements': self.author.profile.get_stats().get('created_advertisements', 0),
            'total_likes': self.author.profile.get_stats().get('total_likes', 0),
            'total_dislikes': self.author.profile.get_stats().get('total_dislikes', 0),
        }

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    created_advertisements = models.IntegerField(default=0)
    total_likes = models.IntegerField(default=0)
    total_dislikes = models.IntegerField(default=0)

    def __str__(self):
        return f'Profile for {self.user.username}'

    def get_stats(self):
        return {
            'created_advertisements': self.created_advertisements,
            'total_likes': self.total_likes,
            'total_dislikes': self.total_dislikes,
        }

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def create_user_profile_for_existing_users(sender, instance, created, **kwargs):
    if not hasattr(instance, 'profile'):
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


@receiver(post_save, sender=Advertisement)
def update_advertisement_stats(sender, instance, created, **kwargs):
    if created:
        instance.author.profile.created_advertisements += 1
        instance.author.profile.save()
    elif instance.pk:
        instance.author.profile.total_likes += instance.likes.count() - Advertisement.objects.get(pk=instance.pk).likes.count()
        instance.author.profile.total_dislikes += instance.dislikes.count() - Advertisement.objects.get(pk=instance.pk).dislikes.count()
        instance.author.profile.save()

@receiver(pre_delete, sender=Advertisement)
def delete_advertisement_stats(sender, instance, **kwargs):
    instance.author.profile.created_advertisements -= 1
    instance.author.profile.total_likes -= instance.likes.count()
    instance.author.profile.total_dislikes -= instance.dislikes.count()
    instance.author.profile.save()



class Comment(models.Model):
    advertisement = models.ForeignKey(Advertisement, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.advertisement}'

urban_project/board/forms.py
from django import forms
from .models import Advertisement
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ['title', 'content', 'author', 'image']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

urban_project/board/views.py
from django.shortcuts import render, redirect
from board.models import Advertisement
from board.forms import AdvertisementForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator


def logout_view(request):
    logout(request)
    return redirect('home')

#from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import login, authenticate

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/board')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def home(request):
    return render(request, 'home.html')

def advertisement_list(request):
    advertisements = Advertisement.objects.all()
    paginator = Paginator(advertisements, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'board/advertisement_list.html', {'page_obj': page_obj})

def advertisement_detail(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    return render(request, 'board/advertisement_detail.html', {'advertisement': advertisement})

@login_required
def add_advertisement(request):
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            advertisement.save()
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()
    return render(request, 'board/add_advertisement.html', {'form': form})

@login_required
def edit_advertisement(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)
        if form.is_valid():
            form.instance.author = request.user
            form.save()

            return redirect('board:advertisement_detail', pk=advertisement.pk)
            # return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm(instance=advertisement)
    return render(request, 'board/edit_advertisement.html', {'form': form, 'advertisement': advertisement})

@login_required
def delete_advertisement(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        advertisement.delete()
        return redirect('board:advertisement_list')
    return render(request, 'board/delete_advertisement.html', {'advertisement': advertisement})


@login_required
def like_advertisement(request, pk):
    advertisement = get_object_or_404(Advertisement, pk=pk)

    if request.user.profile:
        if request.user in advertisement.likes.all():
            advertisement.likes.remove(request.user)
        else:
            advertisement.likes.add(request.user)

        # Update stats
        request.user.profile.total_likes += 1 if request.user not in advertisement.likes.all() else -1
        request.user.profile.save()
    else:
        # Handle case where user doesn't have a profile
        pass

    return redirect('board:advertisement_detail', pk=advertisement.pk)

@login_required
def dislike_advertisement(request, pk):
    advertisement = get_object_or_404(Advertisement, pk=pk)

    if request.user.profile:
        if request.user in advertisement.dislikes.all():
            advertisement.dislikes.remove(request.user)
        else:
            advertisement.dislikes.add(request.user)

    # Update stats
        advertisement.author.profile.total_dislikes += 1 if request.user not in advertisement.dislikes.all() else -1
        advertisement.author.profile.save()
    else:
        pass
    return redirect('board:advertisement_detail', pk=advertisement.pk)

urban_project/board/templates/board/add_advertisement.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add Advertisement</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>


{% endblock %}

urban_project/board/templates/board/advertisement_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ advertisement.title }}</h1>

<p>{{ advertisement.content }}</p>

<h3>Автор: {{ advertisement.author.username }}</h3>

<h3>Дата создания: {{ advertisement.created_at }}</h3>

{% if advertisement.image %}
    <img src="{{ advertisement.image.url }}" alt="Объявление">
{% endif %}

<h3>Статистика:</h3>
<ul>
    <li>Создано объявлений: {{ advertisement.get_stats.created_advertisements }}</li>
    <li>Лайков: {{ advertisement.get_stats.total_likes }}</li>
    <li>Дизлайков: {{ advertisement.get_stats.total_dislikes }}</li>
</ul>


<h3>Likes: {{ advertisement.total_likes }}</h3>
<form method="post" action="{% url 'board:like_advertisement' advertisement.pk %}">
    {% csrf_token %}
    <button type="submit">Like</button>
</form>

<h3>Dislikes: {{ advertisement.total_dislikes }}</h3>
<form method="post" action="{% url 'board:dislike_advertisement' advertisement.pk %}">
    {% csrf_token %}
    <button type="submit">Dislike</button>
</form>

<a href="{% url 'board:advertisement_list' %}">Вернуться к списку объявлений</a>
{% endblock %}

urban_project/board/templates/board/advertisement_list.html
{% extends "base.html" %}

{% block content %}
<h1>Advertisements</h1>
{% if user.is_authenticated %}
    <a href="{% url 'board:add_advertisement' %}"><button>Add Advertisement</button></a>
{% endif %}
<ul>
  {% for advertisement in page_obj %}
    <li>
      <a href="{% url 'board:advertisement_detail' pk=advertisement.pk %}">
        {% if advertisement.image %}
          <img src="{{ advertisement.image.url }}" alt="Advertisement Image">
        {% endif %}
        {{ advertisement.title }} ({{ advertisement.author.username }})
      </a>
    </li>
  {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% else %}
            <span class="disabled">&laquo;</span>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% else %}
            <span class="disabled">&raquo;</span>
        {% endif %}
    </span>
</div>
{% endblock %}

urban_project/board/templates/board/delete_advertisement.html
{% extends "base.html" %}

{% block title %}Delete course{% endblock %}

{% block content %}
<h1>Delete course "{{ object.title }}"</h1>
<div class="module">
    <form action="" method="post">
        {% csrf_token %}
<!--        <p>Are you sure you want to delete "{{ object }}"?</p>-->
        <p>Are you sure you want to delete?</p>
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock %}

urban_project/board/templates/board/edit_advertisement.html
{% extends 'base.html' %}

{% block content %}

<h1>Edit advertisement</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}